name: Build TWRP (Repack vendor_boot)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Device Tree
        uses: actions/checkout@v4
        with:
          path: device/doogee/P2TH

      - name: Download Stock vendor_boot for Repacking
        run: |
          mkdir -p device/doogee/P2TH/prebuilt
          wget "https://github.com/shahvv-commits/android_device_doogee_P2TH/releases/download/stock-files/vendor_boot.img" -O device/doogee/P2TH/prebuilt/vendor_boot.img

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev default-jdk

      - name: Sync TWRP Source (AOSP 12.1)
        run: |
          mkdir ~/twrp
          cd ~/twrp
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc --all) --force-sync

      - name: Move Device Tree to Source
        run: |
          mkdir -p ~/twrp/device/doogee/P2TH
          cp -r $GITHUB_WORKSPACE/device/doogee/P2TH/* ~/twrp/device/doogee/P2TH/

      - name: Build TWRP vendor_boot
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch omni_P2TH-eng
          mka vendorbootimage

      - name: Upload TWRP Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-P2TH-Images
          path: ~/twrp/out/target/product/P2TH/vendor_boot.img
